--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- environment_variables class
local environment_variables = {}
local environment_variables_mt = {
	__name = "environment_variables";
	__index = environment_variables;
}

local function cast_environment_variables(t)
	return setmetatable(t, environment_variables_mt)
end

local function new_environment_variables(name, description, value)
	return cast_environment_variables({
		["name"] = name;
		["description"] = description;
		["value"] = value;
	})
end

return {
	cast = cast_environment_variables;
	new = new_environment_variables;
}
