--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- groups class
local groups = {}
local groups_mt = {
	__name = "groups";
	__index = groups;
}

local function cast_groups(t)
	return setmetatable(t, groups_mt)
end

local function new_groups(id, name, description, status, created_at, updated_at)
	return cast_groups({
		["id"] = id;
		["name"] = name;
		["description"] = description;
		["status"] = status;
		["created_at"] = created_at;
		["updated_at"] = updated_at;
	})
end

return {
	cast = cast_groups;
	new = new_groups;
}
