--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- inline_object_5 class
local inline_object_5 = {}
local inline_object_5_mt = {
	__name = "inline_object_5";
	__index = inline_object_5;
}

local function cast_inline_object_5(t)
	return setmetatable(t, inline_object_5_mt)
end

local function new_inline_object_5(file)
	return cast_inline_object_5({
		["file"] = file;
	})
end

return {
	cast = cast_inline_object_5;
	new = new_inline_object_5;
}
