--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- inline_object_4 class
local inline_object_4 = {}
local inline_object_4_mt = {
	__name = "inline_object_4";
	__index = inline_object_4;
}

local function cast_inline_object_4(t)
	return setmetatable(t, inline_object_4_mt)
end

local function new_inline_object_4(user_id, group_id, permissions_names)
	return cast_inline_object_4({
		["user_id"] = user_id;
		["group_id"] = group_id;
		["permissions_names"] = permissions_names;
	})
end

return {
	cast = cast_inline_object_4;
	new = new_inline_object_4;
}
