--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- inline_object_3 class
local inline_object_3 = {}
local inline_object_3_mt = {
	__name = "inline_object_3";
	__index = inline_object_3;
}

local function cast_inline_object_3(t)
	return setmetatable(t, inline_object_3_mt)
end

local function new_inline_object_3(id, type)
	return cast_inline_object_3({
		["id"] = id;
		["type"] = type;
	})
end

return {
	cast = cast_inline_object_3;
	new = new_inline_object_3;
}
