--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- inline_object_1 class
local inline_object_1 = {}
local inline_object_1_mt = {
	__name = "inline_object_1";
	__index = inline_object_1;
}

local function cast_inline_object_1(t)
	return setmetatable(t, inline_object_1_mt)
end

local function new_inline_object_1(file)
	return cast_inline_object_1({
		["file"] = file;
	})
end

return {
	cast = cast_inline_object_1;
	new = new_inline_object_1;
}
