--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- inline_response_200_4 class
local inline_response_200_4 = {}
local inline_response_200_4_mt = {
	__name = "inline_response_200_4";
	__index = inline_response_200_4;
}

local function cast_inline_response_200_4(t)
	return setmetatable(t, inline_response_200_4_mt)
end

local function new_inline_response_200_4(id, model_id, file_name, mime_type)
	return cast_inline_response_200_4({
		["id"] = id;
		["model_id"] = model_id;
		["file_name"] = file_name;
		["mime_type"] = mime_type;
	})
end

return {
	cast = cast_inline_response_200_4;
	new = new_inline_response_200_4;
}
