--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- media class
local media = {}
local media_mt = {
	__name = "media";
	__index = media;
}

local function cast_media(t)
	return setmetatable(t, media_mt)
end

local function new_media(id, model_id, model_type, collection_name, name, file_name, mime_type, disk, size, manipulations, custom_properties, responsive_images, order_column)
	return cast_media({
		["id"] = id;
		["model_id"] = model_id;
		["model_type"] = model_type;
		["collection_name"] = collection_name;
		["name"] = name;
		["file_name"] = file_name;
		["mime_type"] = mime_type;
		["disk"] = disk;
		["size"] = size;
		["manipulations"] = manipulations;
		["custom_properties"] = custom_properties;
		["responsive_images"] = responsive_images;
		["order_column"] = order_column;
	})
end

return {
	cast = cast_media;
	new = new_media;
}
