--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- metadata class
local metadata = {}
local metadata_mt = {
	__name = "metadata";
	__index = metadata;
}

local function cast_metadata(t)
	return setmetatable(t, metadata_mt)
end

local function new_metadata(filter, sort_by, sort_order, count, total_pages, current_page, form, last_page, path, per_page, to, total)
	return cast_metadata({
		["filter"] = filter;
		["sort_by"] = sort_by;
		["sort_order"] = sort_order;
		["count"] = count;
		["total_pages"] = total_pages;
		["current_page"] = current_page;
		["form"] = form;
		["last_page"] = last_page;
		["path"] = path;
		["per_page"] = per_page;
		["to"] = to;
		["total"] = total;
	})
end

return {
	cast = cast_metadata;
	new = new_metadata;
}
