--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- notifications class
local notifications = {}
local notifications_mt = {
	__name = "notifications";
	__index = notifications;
}

local function cast_notifications(t)
	return setmetatable(t, notifications_mt)
end

local function new_notifications(id, type, notifiable_type, notifiable_id, data)
	return cast_notifications({
		["id"] = id;
		["type"] = type;
		["notifiable_type"] = notifiable_type;
		["notifiable_id"] = notifiable_id;
		["data"] = data;
	})
end

return {
	cast = cast_notifications;
	new = new_notifications;
}
