--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- notifications_editable class
local notifications_editable = {}
local notifications_editable_mt = {
	__name = "notifications_editable";
	__index = notifications_editable;
}

local function cast_notifications_editable(t)
	return setmetatable(t, notifications_editable_mt)
end

local function new_notifications_editable(id, type, notifiable_type, notifiable_id, data)
	return cast_notifications_editable({
		["id"] = id;
		["type"] = type;
		["notifiable_type"] = notifiable_type;
		["notifiable_id"] = notifiable_id;
		["data"] = data;
	})
end

return {
	cast = cast_notifications_editable;
	new = new_notifications_editable;
}
