--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_permissions_editable class
local process_permissions_editable = {}
local process_permissions_editable_mt = {
	__name = "process_permissions_editable";
	__index = process_permissions_editable;
}

local function cast_process_permissions_editable(t)
	return setmetatable(t, process_permissions_editable_mt)
end

local function new_process_permissions_editable(id, process_id, permission_id, assignable_id, assignable_type)
	return cast_process_permissions_editable({
		["id"] = id;
		["process_id"] = process_id;
		["permission_id"] = permission_id;
		["assignable_id"] = assignable_id;
		["assignable_type"] = assignable_type;
	})
end

return {
	cast = cast_process_permissions_editable;
	new = new_process_permissions_editable;
}
