--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_webhook class
local process_webhook = {}
local process_webhook_mt = {
	__name = "process_webhook";
	__index = process_webhook;
}

local function cast_process_webhook(t)
	return setmetatable(t, process_webhook_mt)
end

local function new_process_webhook()
	return cast_process_webhook({
	})
end

return {
	cast = cast_process_webhook;
	new = new_process_webhook;
}
