--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_request_editable class
local process_request_editable = {}
local process_request_editable_mt = {
	__name = "process_request_editable";
	__index = process_request_editable;
}

local function cast_process_request_editable(t)
	return setmetatable(t, process_request_editable_mt)
end

local function new_process_request_editable(user_id, callable_id, data, status)
	return cast_process_request_editable({
		["user_id"] = user_id;
		["callable_id"] = callable_id;
		["data"] = data;
		["status"] = status;
	})
end

return {
	cast = cast_process_request_editable;
	new = new_process_request_editable;
}
