--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_webhook_editable class
local process_webhook_editable = {}
local process_webhook_editable_mt = {
	__name = "process_webhook_editable";
	__index = process_webhook_editable;
}

local function cast_process_webhook_editable(t)
	return setmetatable(t, process_webhook_editable_mt)
end

local function new_process_webhook_editable()
	return cast_process_webhook_editable({
	})
end

return {
	cast = cast_process_webhook_editable;
	new = new_process_webhook_editable;
}
