--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_category_editable class
local process_category_editable = {}
local process_category_editable_mt = {
	__name = "process_category_editable";
	__index = process_category_editable;
}

local function cast_process_category_editable(t)
	return setmetatable(t, process_category_editable_mt)
end

local function new_process_category_editable(name, status)
	return cast_process_category_editable({
		["name"] = name;
		["status"] = status;
	})
end

return {
	cast = cast_process_category_editable;
	new = new_process_category_editable;
}
