--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_category class
local process_category = {}
local process_category_mt = {
	__name = "process_category";
	__index = process_category;
}

local function cast_process_category(t)
	return setmetatable(t, process_category_mt)
end

local function new_process_category(name, status, id, created_at, updated_at)
	return cast_process_category({
		["name"] = name;
		["status"] = status;
		["id"] = id;
		["created_at"] = created_at;
		["updated_at"] = updated_at;
	})
end

return {
	cast = cast_process_category;
	new = new_process_category;
}
