--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_with_start_events class
local process_with_start_events = {}
local process_with_start_events_mt = {
	__name = "process_with_start_events";
	__index = process_with_start_events;
}

local function cast_process_with_start_events(t)
	return setmetatable(t, process_with_start_events_mt)
end

local function new_process_with_start_events(process_category_id, name, description, status, user_id, id, created_at, updated_at, start_events)
	return cast_process_with_start_events({
		["process_category_id"] = process_category_id;
		["name"] = name;
		["description"] = description;
		["status"] = status;
		["user_id"] = user_id;
		["id"] = id;
		["created_at"] = created_at;
		["updated_at"] = updated_at;
		["startEvents"] = start_events;
	})
end

return {
	cast = cast_process_with_start_events;
	new = new_process_with_start_events;
}
