--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_request_token class
local process_request_token = {}
local process_request_token_mt = {
	__name = "process_request_token";
	__index = process_request_token;
}

local function cast_process_request_token(t)
	return setmetatable(t, process_request_token_mt)
end

local function new_process_request_token(user_id, status, due_at, initiated_at, riskchanges_at, id, process_id, process_request_id, element_id, element_type, created_at, updated_at)
	return cast_process_request_token({
		["user_id"] = user_id;
		["status"] = status;
		["due_at"] = due_at;
		["initiated_at"] = initiated_at;
		["riskchanges_at"] = riskchanges_at;
		["id"] = id;
		["process_id"] = process_id;
		["process_request_id"] = process_request_id;
		["element_id"] = element_id;
		["element_type"] = element_type;
		["created_at"] = created_at;
		["updated_at"] = updated_at;
	})
end

return {
	cast = cast_process_request_token;
	new = new_process_request_token;
}
