--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_editable class
local process_editable = {}
local process_editable_mt = {
	__name = "process_editable";
	__index = process_editable;
}

local function cast_process_editable(t)
	return setmetatable(t, process_editable_mt)
end

local function new_process_editable(process_category_id, name, description, status)
	return cast_process_editable({
		["process_category_id"] = process_category_id;
		["name"] = name;
		["description"] = description;
		["status"] = status;
	})
end

return {
	cast = cast_process_editable;
	new = new_process_editable;
}
