--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_request_token_editable class
local process_request_token_editable = {}
local process_request_token_editable_mt = {
	__name = "process_request_token_editable";
	__index = process_request_token_editable;
}

local function cast_process_request_token_editable(t)
	return setmetatable(t, process_request_token_editable_mt)
end

local function new_process_request_token_editable(user_id, status, due_at, initiated_at, riskchanges_at)
	return cast_process_request_token_editable({
		["user_id"] = user_id;
		["status"] = status;
		["due_at"] = due_at;
		["initiated_at"] = initiated_at;
		["riskchanges_at"] = riskchanges_at;
	})
end

return {
	cast = cast_process_request_token_editable;
	new = new_process_request_token_editable;
}
