--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- process_start_events class
local process_start_events = {}
local process_start_events_mt = {
	__name = "process_start_events";
	__index = process_start_events;
}

local function cast_process_start_events(t)
	return setmetatable(t, process_start_events_mt)
end

local function new_process_start_events()
	return cast_process_start_events({
	})
end

return {
	cast = cast_process_start_events;
	new = new_process_start_events;
}
