--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- screens class
local screens = {}
local screens_mt = {
	__name = "screens";
	__index = screens;
}

local function cast_screens(t)
	return setmetatable(t, screens_mt)
end

local function new_screens(id, name, title, type, description, config)
	return cast_screens({
		["id"] = id;
		["name"] = name;
		["title"] = title;
		["type"] = type;
		["description"] = description;
		["config"] = config;
	})
end

return {
	cast = cast_screens;
	new = new_screens;
}
