--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- screens_editable class
local screens_editable = {}
local screens_editable_mt = {
	__name = "screens_editable";
	__index = screens_editable;
}

local function cast_screens_editable(t)
	return setmetatable(t, screens_editable_mt)
end

local function new_screens_editable(id, name, title, type, description, config)
	return cast_screens_editable({
		["id"] = id;
		["name"] = name;
		["title"] = title;
		["type"] = type;
		["description"] = description;
		["config"] = config;
	})
end

return {
	cast = cast_screens_editable;
	new = new_screens_editable;
}
