--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- screen_category class
local screen_category = {}
local screen_category_mt = {
	__name = "screen_category";
	__index = screen_category;
}

local function cast_screen_category(t)
	return setmetatable(t, screen_category_mt)
end

local function new_screen_category(name, status)
	return cast_screen_category({
		["name"] = name;
		["status"] = status;
	})
end

return {
	cast = cast_screen_category;
	new = new_screen_category;
}
