--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- scripts class
local scripts = {}
local scripts_mt = {
	__name = "scripts";
	__index = scripts;
}

local function cast_scripts(t)
	return setmetatable(t, scripts_mt)
end

local function new_scripts(id, title, description, language, code, teimout)
	return cast_scripts({
		["id"] = id;
		["title"] = title;
		["description"] = description;
		["language"] = language;
		["code"] = code;
		["teimout"] = teimout;
	})
end

return {
	cast = cast_scripts;
	new = new_scripts;
}
