--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- scripts_editable class
local scripts_editable = {}
local scripts_editable_mt = {
	__name = "scripts_editable";
	__index = scripts_editable;
}

local function cast_scripts_editable(t)
	return setmetatable(t, scripts_editable_mt)
end

local function new_scripts_editable(id, title, description, language, code, teimout)
	return cast_scripts_editable({
		["id"] = id;
		["title"] = title;
		["description"] = description;
		["language"] = language;
		["code"] = code;
		["teimout"] = teimout;
	})
end

return {
	cast = cast_scripts_editable;
	new = new_scripts_editable;
}
