--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- task_metadata class
local task_metadata = {}
local task_metadata_mt = {
	__name = "task_metadata";
	__index = task_metadata;
}

local function cast_task_metadata(t)
	return setmetatable(t, task_metadata_mt)
end

local function new_task_metadata(filter, sort_by, sort_order, count, total_pages, current_page, form, last_page, path, per_page, to, total, in_overdue)
	return cast_task_metadata({
		["filter"] = filter;
		["sort_by"] = sort_by;
		["sort_order"] = sort_order;
		["count"] = count;
		["total_pages"] = total_pages;
		["current_page"] = current_page;
		["form"] = form;
		["last_page"] = last_page;
		["path"] = path;
		["per_page"] = per_page;
		["to"] = to;
		["total"] = total;
		["in_overdue"] = in_overdue;
	})
end

return {
	cast = cast_task_metadata;
	new = new_task_metadata;
}
