--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- task_assignments class
local task_assignments = {}
local task_assignments_mt = {
	__name = "task_assignments";
	__index = task_assignments;
}

local function cast_task_assignments(t)
	return setmetatable(t, task_assignments_mt)
end

local function new_task_assignments(id, process_id, process_task_id, assignment_id, assignment_type)
	return cast_task_assignments({
		["id"] = id;
		["process_id"] = process_id;
		["process_task_id"] = process_task_id;
		["assignment_id"] = assignment_id;
		["assignment_type"] = assignment_type;
	})
end

return {
	cast = cast_task_assignments;
	new = new_task_assignments;
}
