--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- users class
local users = {}
local users_mt = {
	__name = "users";
	__index = users;
}

local function cast_users(t)
	return setmetatable(t, users_mt)
end

local function new_users(email, password, firstname, lastname, username, address, city, state, postal, country, phone, fax, cell, title, timezone, datetime_format, language, is_administrator, loggedin_at, status, id, created_at, updated_at)
	return cast_users({
		["email"] = email;
		["password"] = password;
		["firstname"] = firstname;
		["lastname"] = lastname;
		["username"] = username;
		["address"] = address;
		["city"] = city;
		["state"] = state;
		["postal"] = postal;
		["country"] = country;
		["phone"] = phone;
		["fax"] = fax;
		["cell"] = cell;
		["title"] = title;
		["timezone"] = timezone;
		["datetime_format"] = datetime_format;
		["language"] = language;
		["is_administrator"] = is_administrator;
		["loggedin_at"] = loggedin_at;
		["status"] = status;
		["id"] = id;
		["created_at"] = created_at;
		["updated_at"] = updated_at;
	})
end

return {
	cast = cast_users;
	new = new_users;
}
