--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

-- users_editable class
local users_editable = {}
local users_editable_mt = {
	__name = "users_editable";
	__index = users_editable;
}

local function cast_users_editable(t)
	return setmetatable(t, users_editable_mt)
end

local function new_users_editable(email, password, firstname, lastname, username, address, city, state, postal, country, phone, fax, cell, title, timezone, datetime_format, language, is_administrator, loggedin_at, status)
	return cast_users_editable({
		["email"] = email;
		["password"] = password;
		["firstname"] = firstname;
		["lastname"] = lastname;
		["username"] = username;
		["address"] = address;
		["city"] = city;
		["state"] = state;
		["postal"] = postal;
		["country"] = country;
		["phone"] = phone;
		["fax"] = fax;
		["cell"] = cell;
		["title"] = title;
		["timezone"] = timezone;
		["datetime_format"] = datetime_format;
		["language"] = language;
		["is_administrator"] = is_administrator;
		["loggedin_at"] = loggedin_at;
		["status"] = status;
	})
end

return {
	cast = cast_users_editable;
	new = new_users_editable;
}
