--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for pm4-sdk-lua.api.permissions_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("permissions_api", function()
  local pm4-sdk-lua_permissions_api = require "pm4-sdk-lua.api.permissions_api"
  -- unit tests for process_maker_http_controllers_api_permission_controller_update
  describe("process_maker_http_controllers_api_permission_controller_update test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
