--[[
  ProcessMaker API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 1.0.0
  Contact: info@processmaker.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for pm4-sdk-lua.api.task_assignments_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("task_assignments_api", function()
  local pm4-sdk-lua_task_assignments_api = require "pm4-sdk-lua.api.task_assignments_api"
  -- unit tests for create_task_assignments
  describe("create_task_assignments test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for update_task_assignments
  describe("update_task_assignments test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
